const GET_CUSTOMERS_QUEUE = 'GET_CUSTOMERS_QUEUE';
const GET_CUSTOMERS_QUEUE_SUCCESS = 'GET_CUSTOMERS_QUEUE_SUCCESS';
const GET_CUSTOMERS_QUEUE_ERROR = 'GET_CUSTOMERS_QUEUE_ERROR';
const SET_QUEUE_REFRESH_TIMEOUT = 'SET_QUEUE_REFRESH_TIMEOUT';
const CLEAR_QUEUE_REFRESH_TIMEOUT = 'CLEAR_QUEUE_REFRESH_TIMEOUT';

export {
  GET_CUSTOMERS_QUEUE,
  GET_CUSTOMERS_QUEUE_SUCCESS,
  GET_CUSTOMERS_QUEUE_ERROR,
  SET_QUEUE_REFRESH_TIMEOUT,
  CLEAR_QUEUE_REFRESH_TIMEOUT
};