import {SEARCH_ACTION_SET, SEARCH_ACTION_CLEAR} from "./searchActionType.js";
import {
  GET_CUSTOMERS_QUEUE,
  GET_CUSTOMERS_QUEUE_SUCCESS,
  GET_CUSTOMERS_QUEUE_ERROR,
  SET_QUEUE_REFRESH_TIMEOUT,
  CLEAR_QUEUE_REFRESH_TIMEOUT
} from "./customersActionType.js";

export {
  SEARCH_ACTION_SET,
  SEARCH_ACTION_CLEAR,
  GET_CUSTOMERS_QUEUE,
  GET_CUSTOMERS_QUEUE_SUCCESS,
  GET_CUSTOMERS_QUEUE_ERROR,
  SET_QUEUE_REFRESH_TIMEOUT,
  CLEAR_QUEUE_REFRESH_TIMEOUT
};